### ISSUE TITLE
Small fix to ready() function

### ISSUE THREAD

**Issue by cpiekacz** [covrig/homeassistant-hline#1]
The following lines in ready() function produce errors:
```
      '--width': (config.width)+'%' ? (config.width)+'%' : '85%',
      '--height': config.height+'px' ? config.height+'px' : '0px',
```

Here is the fix:
```
      '--width': config.width ? config.width+'%' : '85%',
      '--height': config.height ? config.height+'px' : '0px',
```

You should also init config object like this, otherwise if there is no config defined in yaml file it will produce errors in lines above.
```
var config = this.config || {};
```

**Comment by covrig** [comment]
Fixed. Thanks for checking. I recycled the code from an old project.

**Comment by cpiekacz** [comment]
One more thing (probably you've read my comment before I finished editing it). You should also init config object like this, otherwise if there is no config defined in yaml file it will produce errors in lines above.

```
var config = this.config || {};
```

**Comment by covrig** [comment]
Also fixed that. Thanks.
